server:
  port: 9091
spring:
  application:
    name: search-service
  #配置es连接信息
  data:
    elasticsearch:
      cluster-name: elasticsearch #集群名称
      cluster-nodes: 127.0.0.1:9300 #节点信息，tcp端口，集群可配置192.168.200.128:9301,192.168.200.128:9302,192.168.200.128:9303
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka #注册中心地址