server:
  port: 9092
spring:
  application:
    name: system-service #不识别下划线_
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka #注册中心地址
ribbon:
  ConnectiTimeout: 5000 #设置连接超时时间，默认1s
feign:
  hystrix:
    enabled: true #开启feign熔断器支持
  compression:
    request:
      enabled: true #开启请求压缩
      #以下两个有默认值，可以不配置
      mime-types: text/xml, application/xml, application/json
      min-request-size: 2048 #超过2MB才压缩
    response:
      enabled: true
#声明日志级别
logging:
  level: #直接声明level: debug会把底层的spring日志都打印出来
    com.regino: debug