server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://196.168.200.132:8761/eureka #注册中心地址（Linux虚拟机IP）
    fetch-registry: false #是否从注册中心拉取注册列表
    register-with-eureka: false #是否注册到eureka注册中心
